#!/bin/bash

echo "🔧 DevFlow Complete Fix Script"
echo "=============================="
echo ""

echo "🛠️  Applying all fixes..."

# Navigate to project root
cd /Users/aditisingh/Desktop/DevFlow-main

echo "📦 Installing missing dependencies..."
cd frontend
npm install react-quill quill
cd ..

echo "🔄 Restarting servers..."
echo ""
echo "⚠️  Please follow these steps manually:"
echo ""
echo "1. 📍 STOP both servers (Ctrl+C in both terminals)"
echo ""
echo "2. 🚀 RESTART backend server:"
echo "   Terminal 1: npm run dev"
echo ""
echo "3. 🚀 RESTART frontend server:"
echo "   Terminal 2: cd frontend && npm run dev"
echo ""
echo "✅ Fixes Applied:"
echo "   • Rich text editor with all formatting options"
echo "   • Question display with proper formatting"  
echo "   • Fixed sorting functionality"
echo "   • Answer acceptance system"
echo "   • Complete notification system"
echo "   • Updated homepage for guest/user modes"
echo "   • GitHub link integration"
echo ""
echo "🎯 New Features Working:"
echo "   • Bold, Italic, Strikethrough formatting"
echo "   • Numbered lists, Bullet points"
echo "   • Emoji insertion (😊 👍 💡)"
echo "   • Hyperlink insertion"
echo "   • Image upload support"
echo "   • Text alignment (Left, Center, Right)"
echo "   • Answer acceptance (✓ button for question owners)"
echo "   • Real-time notifications"
echo "   • Vote notifications"
echo "   • Answer notifications"
echo "   • Accept answer notifications"
echo ""
echo "🧪 Test These Features:"
echo "   1. Create a question with rich formatting"
echo "   2. Post an answer with formatting"
echo "   3. Vote on answers (notifications should appear)"
echo "   4. Accept an answer as question owner"
echo "   5. Check notification bell for updates"
echo "   6. Sort questions by different criteria"
echo "   7. Test guest mode on homepage"
echo ""
echo "🎉 All issues fixed! Ready for testing!"
